# People with ArtsdataID and WikidataID who have performed at recent events

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?ArtsdataID (SAMPLE(?name) AS ?artist_name) (GROUP_CONCAT(DISTINCT str(?occupation); separator=", ") AS ?occupations) ?WikidataID (SAMPLE(?event) AS ?performed_event) 
{
   VALUES ?artist_type { schema:Person schema:Organization}
  ?ArtsdataID a ?artist_type ;
    schema:name ?name .
  ?event schema:performer ?ArtsdataID .
  OPTIONAL {  ?ArtsdataID schema:sameAs ?WikidataID .  FILTER (regex(str(?WikidataID), "wikidata.org/entity")) }
  OPTIONAL { ?ArtsdataID schema:hasOccupation ?occupation . }
} 
GROUP BY ?ArtsdataID  ?WikidataID 
LIMIT 100
