PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT distinct ?catalog ?label (count( distinct ?event) as ?upcoming_events) 
WHERE {  
  ?catalog a dcat:Catalog ; 
    rdfs:label ?label ;
    schema:hasPart ?g .
  ?event a schema:Event .
  graph ?g {?event schema:startDate ?date }
  filter(?date > 'DATE_PLACEHOLDER'^^xsd:dateTime)
} 
group by ?catalog ?label
