# Upcoming events in Artsdata.ca

PREFIX schema: <http://schema.org/>
SELECT DISTINCT  ?start   (sample(?label) as ?name)  (sample(?url) as ?webpage)
WHERE {
  ?e a schema:Event ; 
  schema:startDate ?start ;
  schema:name ?label ;
  schema:url ?url .
   
  FILTER(?start > 'DATE_PLACEHOLDER'^^xsd:dateTime)
} 
GROUP BY ?start
LIMIT 1000
