# Upcoming events in Artsdata.ca

PREFIX schema: <http://schema.org/>
SELECT distinct  ?start ?status ?mode (sample(?label) as ?name)  (sample(?url) as ?webpage)
WHERE {
  ?e a schema:Event ;
     schema:startDate ?start ;
     schema:name ?label ;
     schema:url ?url ;
     schema:eventStatus ?status ;
     schema:eventAttendanceMode ?mode .
  filter(?start > 'DATE_PLACEHOLDER'^^xsd:dateTime)
} 
group by ?start ?status ?mode
LIMIT 1000
