# Upcoming events in Artsdata.ca core dataset

PREFIX schema: <http://schema.org/>
SELECT *
FROM <http://kg.artsdata.ca/core>
WHERE {
  ?event a schema:Event ;
     schema:startDate ?start ;
     schema:name ?label ;
     schema:location ?location ;
     schema:url ?url ;
     schema:eventStatus ?status .
  FILTER(?start > now())
}  ORDER BY ?start
LIMIT 100
