# Organizations in Artsdata.ca core dataset

PREFIX schema: <http://schema.org/>

SELECT  * 
WHERE {
  ?ArtsdataID a schema:Organization  ; 
    schema:name ?name .
  OPTIONAL { 
    ?ArtsdataID schema:sameAs ?WikidataID . 
    filter (regex(str(?WikidataID), "wikidata.org/entity")) 
  }
} 

ORDER BY ?name 
