# Places in Artsdata.ca core dataset

PREFIX schema: <http://schema.org/>

SELECT  * 
WHERE {
  
  ?ArtsdataID a schema:Place  .
  
  ?ArtsdataID schema:name ?label .
  filter (lang(?label) = "") 
  
  OPTIONAL { ?ArtsdataID schema:containedInPlace/schema:name ?containedIn  filter (lang(?containedIn) = "") }
  OPTIONAL { ?ArtsdataID schema:sameAs ?WikidataID . filter (regex(str(?WikidataID), "wikidata.org/entity")) }
  OPTIONAL { ?ArtsdataID schema:address/schema:streetAddress ?address . }
  OPTIONAL { ?ArtsdataID schema:address/schema:addressLocality ?locality . }
  OPTIONAL { ?ArtsdataID schema:address/schema:addressCountry ?country . }

  filter (isURI(?ArtsdataID))
} 
ORDER BY ASC(?ArtsdataID)

LIMIT 100